# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
    
    - name: build
      run: dotnet publish /p:AssemblyVersion=1.${{ steps.version.outputs.version }} ./src --output Cs2PracticeMode

    - name: generate linux asset name
      id : linux-asset-name
      run: echo "NAME=cs2-practice-mode-linux-${{ steps.version.outputs.version }}.tar.gz" >> $GITHUB_OUTPUT
    
    - name: prepare release artifact
      run: tar -czvf ${{ steps.linux-asset-name.outputs.NAME }} Cs2PracticeMode
   
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.linux-asset-name.outputs.NAME }}
        path: ${{ steps.linux-asset-name.outputs.NAME }}
    
    - name: release
      uses: softprops/action-gh-release@v2
      with:
          fail_on_unmatched_files: true
          files: ${{ steps.linux-asset-name.outputs.NAME }}
          tag_name: ${{ steps.version.outputs.version }}
